name: 'Terraform'

on:
  create:
    tags:
      - "v*"
  push:
    branches:
      - "dev"
      - "releases/*"
  pull_request:
    branches:
      - "dev"
      - "releases/*"

permissions:
  contents: write
  id-token: write
jobs:
  terraform-dev:
    name: 'TerraformDev'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_RG_NAME: ${{ secrets.TF_RG_NAME }}
      TF_SANAME: ${{ secrets.TF_SANAME }}
      TF_CONTAINERNAME: ${{ secrets.TF_CONTAINERNAME }}
      environment: dev
      tf_actions_working_dir: ./tf
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.tf_actions_working_dir }}
    if:  (github.event.pull_request.base.ref == 'dev' ) || (github.ref == 'refs/heads/dev')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          client-id: ${{ env.ARM_CLIENT_ID }}
      - name: 'Check azure terraform backend'
        run: sh check_tfstate.sh ${{ env.TF_RG_NAME }} ${{ env.TF_SANAME }} ${{ env.TF_CONTAINERNAME }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: 'Terraform Init'
        id: init
        run: |
          terraform init
          terraform workspace select ${{ env.environment }} || terraform workspace new ${{ env.environment }}
      - name: 'Terraform fmt'
        run: terraform fmt -check
      - name: 'Terraform Validate'
        run: terraform validate
        continue-on-error: true
      - name: 'Terraform Plan'
        run: terraform plan -var-file=${{ env.environment }}.tfvars -out=plan.out
        continue-on-error: false

      - name: 'Terraform Plan Status'
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: terraform apply
        if: (github.ref == 'refs/heads/dev')
        run: |
          terraform apply plan.out
        shell: bash

  terraform-nonprod:
    name: 'TerraformNonprod'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_RG_NAME: ${{ secrets.TF_RG_NAME }}
      TF_SANAME: ${{ secrets.TF_SANAME }}
      TF_CONTAINERNAME: ${{ secrets.TF_CONTAINERNAME }}
      environment: nonprod
      tf_actions_working_dir: ./tf
    runs-on: ubuntu-latest
    environment: nonprod


    if: startsWith(github.event.pull_request.base.ref, 'releases/') || startsWith(github.ref, 'refs/heads/releases/')

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          client-id: ${{ env.ARM_CLIENT_ID }}
      - name: 'check azure terraform backend'
        run: sh check_tfstate.sh ${{ env.TF_RG_NAME }} ${{ env.TF_SANAME }} ${{ env.TF_CONTAINERNAME }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: 'Terraform Init'
        id: init
        run: |
          terraform init
          terraform workspace select ${{ env.environment }} || terraform workspace new ${{ env.environment }}
      - name: Terraform
        run: terraform fmt -check
      - name: 'Terraform Validate'
        run: terraform validate
        continue-on-error: true
      - name: 'Terraform Plan'
        run: terraform plan -var-file=${{ env.environment }}.tfvars -out=plan.out
        continue-on-error: false

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: terraform apply
        if:  startsWith(github.ref, 'refs/heads/releases/')
        run: |
          terraform apply plan.out
        shell: bash

  terraform-prod:
    name: 'TerraformProd'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_RG_NAME: ${{ secrets.TF_RG_NAME }}
      TF_SANAME: ${{ secrets.TF_SANAME }}
      TF_CONTAINERNAME: ${{ secrets.TF_CONTAINERNAME }}
      environment: production
      tf_actions_working_dir: ./tf
    runs-on: ubuntu-latest
    environment: production
    if: startsWith(github.ref, 'refs/tags/')
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          client-id: ${{ env.ARM_CLIENT_ID }}
      - name: 'check azure terraform backend'
        run:  sh check_tfstate.sh ${{ env.TF_RG_NAME }} ${{ env.TF_SANAME }} ${{ env.TF_CONTAINERNAME }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: 'Terraform Init'
        id: init
        run: |
          terraform init
          terraform workspace select ${{ env.environment }} || terraform workspace new ${{ env.environment }}
      - name: Terraform
        run: terraform fmt -check
      - name: 'Terraform Validate'
        run: terraform validate
        continue-on-error: true
      - name: 'Terraform Plan'
        run: terraform plan -var-file=${{ env.environment }}.tfvars -out=plan.out
        continue-on-error: false

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: terraform apply
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          terraform apply plan.out
        shell: bash
